// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBesNpuFW6Nid994gX97wy9TVmxcuoys64',
    appId: '1:128035627461:web:4a908bd3974b0efc73ebac',
    messagingSenderId: '128035627461',
    projectId: 'my-flutter-food-app',
    authDomain: 'my-flutter-food-app.firebaseapp.com',
    storageBucket: 'my-flutter-food-app.appspot.com',
    measurementId: 'G-MFGWPKZL2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnH8xJtvnAj-8a1BZq93mTKj1oLwV_gEo',
    appId: '1:128035627461:android:694e954fb9b7277a73ebac',
    messagingSenderId: '128035627461',
    projectId: 'my-flutter-food-app',
    storageBucket: 'my-flutter-food-app.appspot.com',
  );

}